### ISSUE TITLE
9.4.11: ISPN000026: Caught exception purging data container!: java.lang.NullPointerException

### ISSUE THREAD

**Issue by faevourite** [infinispan/infinispan-cachestore-cassandra#24]
To reproduce:
1. Configure the cache-container as follows:
```xml
<cache-container name="local" default-cache="default" statistics="true">
    <local-cache name="default"/>
    <local-cache name="sessions">
        <persistence>
            <store class="org.infinispan.persistence.cassandra.CassandraStore" shared="true">
                <property name="keyspace">foo</property>
                <property name="entryTable">bar</property>
                <property name="readConsistencyLevel">LOCAL_ONE</property>
                <property name="readSerialConsistencyLevel">SERIAL</property>
                <property name="writeConsistencyLevel">QUORUM</property>
                <property name="writeSerialConsistencyLevel">SERIAL</property>
                <property name="autoCreateKeyspace">true</property>
                <property name="replicationStrategy">{'class':'SimpleStrategy','replication_factor':1}</property>
                <property name="compression">{'sstable_compression':'LZ4Compressor'}</property>
                <property name="useSsl">false</property>
                <property name="servers">localhost[9042]</property>
                <property name="connectionPool.heartbeatIntervalSeconds">30</property>
                <property name="connectionPool.idleTimeoutSeconds">120</property>
                <property name="connectionPool.poolTimeoutMillis">2000</property>
            </store>
        </persistence>
    </local-cache>
</cache-container>
```
2. Build and copy `infinispan-cachestore-cassandra-9.4.1-SNAPSHOT-jar-with-dependencies.jar` into `standalone/deployments/` inside the ISPN distribution. I used [this commit](51a2a883e2c8a4e1c198d0728d426843a0fd5ec8).
3. Run cassandra on the same host.
4. Run `standalone.sh` with the modified config file.

After starting the following message will appear in the logs at regular intervals:
```
WARN  [org.infinispan.persistence.manager.PersistenceManagerImpl] (pool-9-thread-1) ISPN000026: Caught exception purging data container!: java.lang.NullPointerException
	at org.infinispan.core:ispn-9.4@9.4.11.Final//org.infinispan.persistence.manager.PersistenceManagerImpl.lambda$purgeExpired$6(PersistenceManagerImpl.java:454)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.infinispan.core:ispn-9.4@9.4.11.Final//org.infinispan.persistence.manager.PersistenceManagerImpl.purgeExpired(PersistenceManagerImpl.java:465)
	at org.infinispan.core:ispn-9.4@9.4.11.Final//org.infinispan.expiration.impl.ExpirationManagerImpl.processExpiration(ExpirationManagerImpl.java:111)
	at org.infinispan.core:ispn-9.4@9.4.11.Final//org.infinispan.expiration.impl.ExpirationManagerImpl$ScheduledTask.run(ExpirationManagerImpl.java:245)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Note: I'm actually running the docker container in the last step above, but I get the same error when running ISPN natively on a Mac (Mojave).

**Comment by ryanemerson** [comment]
@faevourite The cause of the NPE is that the transport variable is null in the PersistenceManager. We attempt to utilise this object to determine if the current node is the coordinator when a store is set to shared. However, when a cache is not clustered, i.e. local-cache in your example, the transport will always be null. Ultimately, Infinispan should not allow a local-cache to have a shared store, so I have created a Jira and required PRs: https://issues.jboss.org/browse/ISPN-10095

For your use-case, simply remove the shared attribute or set it to false and the NPE should disappear.
